platform=Web
baseUrl=https://www.bilyoner.com
appiumServerUrl=http://127.0.0.1:4723
# Android
deviceName=emulator-5554
platformVersion=13.0
appPackage=com.bilyoner.android
appActivity=com.bilyoner.android.MainActivity
# iOS
iosDeviceName=iPhone 15
iosPlatformVersion=17.0
iosBundleId=com.bilyoner.ios
explicitWait=10
