explicitWait=10
platform=iOS
deviceName=iPhone 17 Pro
appiumServerUrl=http://127.0.0.1:4723
#androidAppPath=src/main/resources/apps/mda-2.2.0-25.apk
iosAppPath=/Users/emresarikaya/IdeaProjects/Java/src/main/resources/apps/SauceLabs-Demo-App.Simulator.zip
