platform=Android
deviceName=emulator-5554
platformVersion=13.0
appPackage=com.bilyoner.android
appActivity=com.bilyoner.android.MainActivity
baseUrl=https://www.bilyoner.com
appiumServerUrl=http://127.0.0.1:4723

explicitWait=10